"""initial schema

Revision ID: 52b5d3047141
Revises: 
Create Date: 2026-05-06 21:50:23.627424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b5d3047141'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('jurisdiction_level', sa.String(), nullable=False),
    sa.Column('file_number', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('body_name', sa.String(), nullable=True),
    sa.Column('intro_date', sa.DateTime(), nullable=True),
    sa.Column('agenda_date', sa.DateTime(), nullable=True),
    sa.Column('passed_date', sa.DateTime(), nullable=True),
    sa.Column('enactment_number', sa.String(), nullable=True),
    sa.Column('enactment_date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', 'city', name='uq_source_bill')
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index('ix_bills_agenda_date', ['agenda_date'], unique=False)
        batch_op.create_index('ix_bills_city', ['city'], unique=False)
        batch_op.create_index('ix_bills_intro_date', ['intro_date'], unique=False)
        batch_op.create_index('ix_bills_jurisdiction_level', ['jurisdiction_level'], unique=False)
        batch_op.create_index('ix_bills_status', ['status'], unique=False)
        batch_op.create_index('ix_bills_type_name', ['type_name'], unique=False)

    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collections_slug'), ['slug'], unique=True)

    op.create_table('officials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('party', sa.String(), nullable=True),
    sa.Column('body_name', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'city', name='uq_official_source')
    )
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.create_index('ix_officials_active', ['active'], unique=False)
        batch_op.create_index('ix_officials_city', ['city'], unique=False)

    op.create_table('story_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('feed_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('fetch_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_url')
    )
    with op.batch_alter_table('story_sources', schema=None) as batch_op:
        batch_op.create_index('ix_story_sources_city', ['city'], unique=False)

    op.create_table('bill_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=True),
    sa.Column('action_text', sa.String(), nullable=True),
    sa.Column('body_name', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('mover_id', sa.Integer(), nullable=True),
    sa.Column('seconder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mover_id'], ['officials.id'], ),
    sa.ForeignKeyConstraint(['seconder_id'], ['officials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_actions', schema=None) as batch_op:
        batch_op.create_index('ix_bill_actions_bill_id', ['bill_id'], unique=False)
        batch_op.create_index('ix_bill_actions_mover_id', ['mover_id'], unique=False)
        batch_op.create_index('ix_bill_actions_seconder_id', ['seconder_id'], unique=False)

    op.create_table('bill_briefings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('organizing', sa.Text(), nullable=True),
    sa.Column('reception', sa.Text(), nullable=True),
    sa.Column('news_json', sa.Text(), nullable=True),
    sa.Column('power_analysis', sa.Text(), nullable=True),
    sa.Column('narrative_json', sa.Text(), nullable=True),
    sa.Column('coalition_json', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id')
    )
    op.create_table('bill_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'url', name='uq_bill_document')
    )
    with op.batch_alter_table('bill_documents', schema=None) as batch_op:
        batch_op.create_index('ix_bill_documents_bill_id', ['bill_id'], unique=False)

    op.create_table('bill_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('embedding_json', sa.Text(), nullable=True),
    sa.Column('embedding_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('similar_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id')
    )
    op.create_table('bill_sponsors',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id', 'official_id')
    )
    op.create_table('bill_topics',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bill_id', 'topic_name')
    )
    with op.batch_alter_table('bill_topics', schema=None) as batch_op:
        batch_op.create_index('ix_bill_topics_bill_id', ['bill_id'], unique=False)
        batch_op.create_index('ix_bill_topics_topic_name', ['topic_name'], unique=False)

    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'bill_id', name='uq_collection_bill')
    )
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.create_index('ix_collection_items_bill_id', ['bill_id'], unique=False)
        batch_op.create_index('ix_collection_items_collection_id', ['collection_id'], unique=False)

    op.create_table('stories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('city_name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('relevant', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('classified_at', sa.DateTime(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['story_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_url')
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index('ix_stories_category', ['category'], unique=False)
        batch_op.create_index('ix_stories_city', ['city'], unique=False)
        batch_op.create_index('ix_stories_published_at', ['published_at'], unique=False)
        batch_op.create_index('ix_stories_relevant', ['relevant'], unique=False)
        batch_op.create_index('ix_stories_source_id', ['source_id'], unique=False)

    op.create_table('vote_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('official_id', sa.Integer(), nullable=False),
    sa.Column('vote_value', sa.String(), nullable=False),
    sa.Column('vote_date', sa.DateTime(), nullable=True),
    sa.Column('action_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['official_id'], ['officials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id', 'official_id', name='uq_vote_bill_official')
    )
    with op.batch_alter_table('vote_records', schema=None) as batch_op:
        batch_op.create_index('ix_vote_records_bill_id', ['bill_id'], unique=False)
        batch_op.create_index('ix_vote_records_official_id', ['official_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_records', schema=None) as batch_op:
        batch_op.drop_index('ix_vote_records_official_id')
        batch_op.drop_index('ix_vote_records_bill_id')

    op.drop_table('vote_records')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index('ix_stories_source_id')
        batch_op.drop_index('ix_stories_relevant')
        batch_op.drop_index('ix_stories_published_at')
        batch_op.drop_index('ix_stories_city')
        batch_op.drop_index('ix_stories_category')

    op.drop_table('stories')
    with op.batch_alter_table('collection_items', schema=None) as batch_op:
        batch_op.drop_index('ix_collection_items_collection_id')
        batch_op.drop_index('ix_collection_items_bill_id')

    op.drop_table('collection_items')
    with op.batch_alter_table('bill_topics', schema=None) as batch_op:
        batch_op.drop_index('ix_bill_topics_topic_name')
        batch_op.drop_index('ix_bill_topics_bill_id')

    op.drop_table('bill_topics')
    op.drop_table('bill_sponsors')
    op.drop_table('bill_embeddings')
    with op.batch_alter_table('bill_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_bill_documents_bill_id')

    op.drop_table('bill_documents')
    op.drop_table('bill_briefings')
    with op.batch_alter_table('bill_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_bill_actions_seconder_id')
        batch_op.drop_index('ix_bill_actions_mover_id')
        batch_op.drop_index('ix_bill_actions_bill_id')

    op.drop_table('bill_actions')
    with op.batch_alter_table('story_sources', schema=None) as batch_op:
        batch_op.drop_index('ix_story_sources_city')

    op.drop_table('story_sources')
    with op.batch_alter_table('officials', schema=None) as batch_op:
        batch_op.drop_index('ix_officials_city')
        batch_op.drop_index('ix_officials_active')

    op.drop_table('officials')
    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collections_slug'))

    op.drop_table('collections')
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index('ix_bills_type_name')
        batch_op.drop_index('ix_bills_status')
        batch_op.drop_index('ix_bills_jurisdiction_level')
        batch_op.drop_index('ix_bills_intro_date')
        batch_op.drop_index('ix_bills_city')
        batch_op.drop_index('ix_bills_agenda_date')

    op.drop_table('bills')
    # ### end Alembic commands ###
